### ISSUE TITLE
Add possibility to add own sections in DEPENDENCIES.md

### ISSUE THREAD

**Issue by cheeZery** [cheeZery/depdoc#1]
Currently there's no way to add own sections to the markdown, they will be removed everytime you run ``depoc update``. Own sections preceded with ``###`` should stay in DEPENDENCIES.md after an update.

**Comment by GodLesZ** [comment]
What exactly do you mean @cheeZery? What kind of sections?

**Comment by cheeZery** [comment]
I had a discussion with a colleague of mine who mentioned that the predecessor of our dependency documentation (json5 file) offered the possibility to add other information to the file (such as links to wiki pages, etc).
Still not sure, if this is needed and should be added here. Maybe we should close the issue.

**Comment by GodLesZ** [comment]
IMHO the general readme file should be used for this.
But it would be an easy task to define a "starting point" which is marked with `---- depdoc ----` (or w/e) and put everything just after that.

But currently I don't see any useful case for it.
The DEPENDENCIES file should be used for dependencies :blush:

**Comment by cheeZery** [comment]
I agree with you, @GodLesZ
