### ISSUE TITLE
Improve determining Composer package versions

### ISSUE THREAD

**Issue by cheeZery** [cheeZery/depdoc#15]
When running depdoc (either validate or update) what's take the longest is determining the installed packages of Composer and npm. Also we do this by executing a CLI command, there should be better ways to do this.

I found [Ocramius/PackageVersions](https://github.com/Ocramius/PackageVersions) which offers a nice utility function to get the installed version of a specific Composer package. Maybe it can be enhanced to get versions of all (directly) required packages.
I also saw that they ingeniously read the installed versions after install or update (see [here](https://github.com/Ocramius/PackageVersions/blob/master/composer.json#L39)).
They're also requiring composer/composer directly, which to me seems to be a lot better than running a CLI command and parsing the output (they also require "composer-plugin-api", which might be the actual way to use Composer stuff in your project).
There's also [Rinvex Composer](https://github.com/rinvex/composer) which promotes itself as an "intuitive package that utilizes Composer Plugin API".

**Comment by reinfi** [comment]
Could be closed now, thanks for merge.

**Comment by cheeZery** [comment]
Fixed with #17
