### ISSUE TITLE
Referencing zend-framework/service-manager

### ISSUE THREAD

**Issue by reinfi** [cheeZery/depdoc#18]
Hey,

why is there a requirement of the zend-framework/service-manager?

Can not find any usage?

**Comment by GodLesZ** [comment]
Oh sorry this ist my fault - I wanted to use it for depency injection but didn't hat time yet to creare a PR.

**Comment by reinfi** [comment]
Good idea, but as we are using several Symfony packages, would it be a better idea to use Symfony container?

**Comment by GodLesZ** [comment]
For sure :)
Any PSR-11 compliant is better than no one I guess.

Lemme take a look into Symfony; never touched them beside the excellent `Console Application`

**Comment by reinfi** [comment]
I am on it, resolving it with symfony di.
