### ISSUE TITLE
Strict mode for validate command

### ISSUE THREAD

**Issue by reinfi** [cheeZery/depdoc#20]
Actually the validate command just checks the presence of the packages, i.e. if one is removed or one added but not documented.
It also checks the pinned versions if there installed version matches.

I would like to have a --strict mode for the validate command which then validated all versions to be equal to the one documented.

Any opinions on that?

**Comment by GodLesZ** [comment]
Good point, I rly didn't knew this is an issue but yes it is.
I like the `--strict` idea.

Maybe we should also add a level of strictness?
The default level just checks for major & minor part, but an e.g. `--very-strict` also checks the bugfix/full version?

**Comment by cheeZery** [comment]
Cool idea!
