### ISSUE TITLE
Add possiblity to configure depdoc usage

### ISSUE THREAD

**Issue by cheeZery** [cheeZery/depdoc#3]
Options which should be included
- Used lock symbol
- Toggle description in DEPENDECIES.md
- Toggle external link in DEPENDECIES.md (link not yet implemented, see #2)
- Exclude package manager
- ~~Toggle table of contents in MD file (if included, see #4)~~

Decide which config file format to use (should probably be json, yaml, or both).

**Comment by cheeZery** [comment]
@reinfi, @GodLesZ, what do you guys think? In #8 we'll get some more CLI arguments. Shoud those generally prefered over a config file? I guess a lot of big projects offer both CLI args and config files.

**Comment by GodLesZ** [comment]
I like tool configuration files. It's more robust than CLI arguments.
Also JSON & YAML files are a good standard nowadays so yes :+1:

**Comment by reinfi** [comment]
Definitely a configuration file. So dep-doc can always run as configured. json or yaml or xml or whatever.

**Comment by GodLesZ** [comment]
fyi I'm working on it

**Comment by GodLesZ** [comment]
My girlfriend will cut me down :laughing:
