### ISSUE TITLE
Consider adding table of contents

### ISSUE THREAD

**Issue by cheeZery** [cheeZery/depdoc#4]
Decide wheter it's a good idea to add table of contents at beginning of DEPENDENCIES.md. If so then include it!

**Comment by GodLesZ** [comment]
Ich don't this is realy usefull.
Modern markdown reader & editor auto-generate a TOC.

Also on bigger projects this won't help as the list of dependencies is still long and so will BE in the TOC.
Maybe just generate a depdoc file from a mid-size project and generate the TOC.
This should help to decide and see If the TOC could be usefull.

**Comment by cheeZery** [comment]
Yeah, that was my concern as well. I will close this issue, thanks for your opinion!
