### ISSUE TITLE
Use system aware line break in DEPENDENCIES.md

### ISSUE THREAD

**Issue by cheeZery** [cheeZery/depdoc#7]
Improve writing of Markdown file by not just using \r\n to end line.

See [MarkdownWriter.php](https://github.com/cheeZery/depdoc/blob/b87d695cc72991cb21135fa35734207887f51f3b/src/Writer/MarkdownWriter.php#L57).

**Comment by reinfi** [comment]
can be closed

**Comment by cheeZery** [comment]
Fixed with #10
